const { title, ref } = require("./sidebars/utils");
const { buildingApps } = require("./sidebars/building-apps");
const { appStore } = require("./sidebars/app-store");
const { developmentBoardQuill } = require("./sidebars/development-board-quill");
const { community } = require("./sidebars/community");
const { selfHosting } = require("./sidebars/self-hosting");
const { extending } = require("./sidebars/extending");
const { cloudSidebar } = require("./sidebars/cloud");
const { upgradeGuidesSidebar } = require("./sidebars/upgrade-guides");
const { recipesSidebar } = require("./sidebars/recipes");

const backToHome = {
  type: "ref",
  id: "index",
  label: "<- Back to home",
  className: "menu__backlink",
  customProps: {
    sidebar_is_backlink: true,
    sidebar_icon: "back-arrow",
  },
};

module.exports = {
  main: [
    {
      type: "doc",
      id: "index",
      label: "Overview",
      customProps: {
        icon: "home",
      },
    },
    {
      type: "category",
      label: "Quickstart",
      items: [
        "quickstart/cloud",
        "quickstart/running-locally",
        "quickstart/storefront",
      ],
      customProps: {
        icon: "play",
      },
    },
    {
      type: "category",
      label: "Why Saleor",
      items: [
        {
          type: "autogenerated",
          dirName: "overview/why-saleor",
        },
      ],
      customProps: {
        icon: "star",
      },
    },

    title("Development Boards"),
    // ref("cloud/overview", "DevKit Series", "devBoard"),
    ref("product/quill", "Quill Series", "feather"),
    ref("developer/index", "Pico Series", "distribute"),
    ref("cloud/overview", "Mesh Cube", "appBoard"),

    title("Modules"),
    ref("cloud/overview", "F6001", "coreModule"),

    title("Projects"),
    ref("developer/app-store/overview", "MeshCube for Meshtastic", "box"),
    ref("developer/app-store/overview", "Solar Power for Meshtastic", "box"),

    title("Extensions"),
    ref("developer/app-store/overview", "Sensors", "thermometer"),
    ref("developer/app-store/overview", "Batteries", "charge"),

    title("Platforms"),
    ref("developer/app-store/overview", "Zephyr RTOS", "platform"),
    ref("developer/app-store/overview", "Arduino", "platform"),
    ref("developer/app-store/overview", "MicroPython", "platform"),

    title("Additional Resources"),
    {
      type: "doc",
      id: "about/index",
      customProps: {
        icon: "info",
      },
    },
    {
      type: "doc",
      id: "license/index",
      customProps: {
        icon: "checklist",
      },
    },
    {
      type: "link",
      label: "Store",
      href: "https://saleor.io/discord",
      customProps: {
        icon: "shop",
      },
    },
    {
      type: "link",
      label: "Report an Issue",
      href: "https://github.com/saleor/saleor-docs/issues/new",
      customProps: {
        icon: "feedback",
      },
    },
    {
      type: "link",
      label: "Join Discord",
      href: "https://saleor.io/discord",
      customProps: {
        icon: "discord",
      },
    },
  ],
  concepts: [backToHome, ...developmentBoardQuill],
  recipes: [backToHome, ...recipesSidebar],
  appStore: [backToHome, ...appStore],
  buildingApps: [backToHome, ...buildingApps],
  extending: [backToHome, ...extending],
  selfHosting: [backToHome, ...selfHosting],
  community: [backToHome, ...community],
  cloud: [backToHome, ...cloudSidebar],
  upgrade: [backToHome, ...upgradeGuidesSidebar],
};
